#:schema node_modules/wrangler/config-schema.json
name = "epesooj-webring"
pages_build_output_dir = "./public"
compatibility_date = "2024-09-27"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "22.8.0"
